version: '2'
services:
    blog_application-app:
        image: blog_application
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://blog_application-postgresql:5432/blog_application
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    blog_application-postgresql:
        extends:
            file: postgresql.yml
            service: blog_application-postgresql
